# Generated by Django 5.1.2 on 2024-10-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='고객',
        #     fields=[
        #         ('고객번호', models.CharField(max_length=5, primary_key=True, serialize=False)),
        #         ('고객회사명', models.CharField(max_length=30)),
        #         ('담당자명', models.CharField(max_length=20)),
        #         ('담당자직위', models.CharField(max_length=20)),
        #         ('주소', models.CharField(max_length=50)),
        #         ('도시', models.CharField(max_length=20)),
        #         ('지역', models.CharField(max_length=20)),
        #         ('전화번호', models.CharField(max_length=20)),
        #         ('마일리지', models.IntegerField()),
        #     ],
        #     options={
        #         'db_table': '고객',
        #     },
        # ),
    ]
