# Generated by Django 5.1.2 on 2024-10-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_MA',
            fields=[
                ('Week_Date', models.DateField(primary_key=True, serialize=False)),
                ('Week_Rank', models.IntegerField()),
                ('Title', models.CharField(max_length=128)),
                ('Artist', models.CharField(max_length=128)),
                ('Production', models.CharField(max_length=128)),
                ('Weekly_Views', models.BigIntegerField()),
                ('Genre', models.CharField(max_length=32)),
                ('Runtime', models.CharField(max_length=32)),
                ('New_Artist', models.CharField(max_length=128)),
                ('n_score', models.FloatField()),
                ('g_score', models.FloatField()),
                ('Rank_lag_1', models.IntegerField()),
                ('Rank_lag_2', models.IntegerField()),
                ('Rank_lag_3', models.IntegerField()),
            ],
            options={
                'db_table': 'TBL_MA',
            },
        ),
        migrations.CreateModel(
            name='고객',
            fields=[
                ('고객번호', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('고객회사명', models.CharField(max_length=30)),
                ('담당자명', models.CharField(max_length=20)),
                ('담당자직위', models.CharField(max_length=20)),
                ('주소', models.CharField(max_length=50)),
                ('도시', models.CharField(max_length=20)),
                ('지역', models.CharField(max_length=20)),
                ('전화번호', models.CharField(max_length=20)),
                ('마일리지', models.IntegerField()),
            ],
            options={
                'db_table': '고객',
            },
        ),
    ]
