# Generated by Django 5.1.2 on 2024-10-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='고객',
        ),
    ]
